apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Simplified Release
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
        description: |
          JSON manifest specifying which components to deploy. Format:
          {
            "hackers-api": {"jamesalts/hackers-api": {"deploy": true, "version": "3.0-19", "id": "uuid"}},
            "hackers-auth": {"jamesalts/hackers-auth": {"deploy": true, "version": "2.0-19", "id": "uuid"}},
            "hackers-web": {"jamesalts/hackers-web": {"deploy": true, "version": "1.0-X", "id": "uuid"}}
          }
metadata:
  stages/v1alpha1:
    - name: Staging
      jobs:
        - parse-manifest
        - deploy-to-staging
        - verify-staging
        - staging-approval
    - name: Production
      jobs:
        - deploy-to-prod
        - run-smoke-tests

jobs:
  parse-manifest:
    steps:
      - name: Display deployment info
        uses: docker://alpine:3.20
        run: |
          echo "=== Simplified Release Pipeline ==="
          echo "Deploying components to staging, then production after approval."
          echo ""
          echo "Components configured via manifest input."
          echo "Check Evidence tab for full manifest details."
      - name: Publish staging deployment evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## Simplified Release Initiated

            **Release Run:** ${{ cloudbees.run_number }}

            ### Deployment Manifest
            ```json
            ${{ inputs.manifest }}
            ```

            ### Release Pipeline
            1. Deploy to Staging
            2. Manual Approval
            3. Deploy to Production
            4. Smoke Tests
          format: MARKDOWN

  deploy-to-staging:
    needs:
      - parse-manifest
    uses: jalts-808/j-hackers-app/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: j-hackers-staging
    secrets: inherit
    vars: inherit

  verify-staging:
    needs:
      - deploy-to-staging
    steps:
      - name: Verify staging services
        uses: docker://alpine:3.20
        id: verify
        run: |
          apk add --no-cache curl

          echo "=== Verifying Staging Deployment ==="

          # Check Web service
          echo "Checking Web service..."
          WEB_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://staging-hackers-web.54.201.69.176.nip.io/ || echo "000")
          if [ "$WEB_STATUS" = "200" ]; then
            echo "Web service: UP (HTTP $WEB_STATUS)"
          else
            echo "Web service: DOWN (HTTP $WEB_STATUS)"
          fi

          # Check API service
          echo "Checking API service..."
          API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://staging-hackers-api.54.201.69.176.nip.io/api/stories || echo "000")
          if [ "$API_STATUS" = "200" ]; then
            echo "API service: UP (HTTP $API_STATUS)"
          else
            echo "API service: DOWN (HTTP $API_STATUS)"
          fi

          # Check Auth service
          echo "Checking Auth service..."
          AUTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://staging-hackers-auth.54.201.69.176.nip.io/ || echo "000")
          if [ "$AUTH_STATUS" = "200" ] || [ "$AUTH_STATUS" = "404" ]; then
            echo "Auth service: UP (HTTP $AUTH_STATUS)"
          else
            echo "Auth service: DOWN (HTTP $AUTH_STATUS)"
          fi

          echo ""
          echo "Staging verification complete."
      - name: Publish verification evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## Staging Verification Results

            | Service | URL | Status |
            |---------|-----|--------|
            | Web | http://staging-hackers-web.54.201.69.176.nip.io | Deployed |
            | API | http://staging-hackers-api.54.201.69.176.nip.io | Deployed |
            | Auth | http://staging-hackers-auth.54.201.69.176.nip.io | Deployed |

            **Next Step:** Awaiting approval for production deployment
          format: MARKDOWN

  staging-approval:
    needs:
      - verify-staging
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      instructions: |
        Staging deployment complete. Please verify the staging environment before approving production deployment.

        **Staging URLs:**
        - Web: http://staging-hackers-web.54.201.69.176.nip.io
        - API: http://staging-hackers-api.54.201.69.176.nip.io
        - Auth: http://staging-hackers-auth.54.201.69.176.nip.io

        Click Approve to proceed with production deployment.
      disallowLaunchByUser: false
      approvers: ""

  deploy-to-prod:
    needs:
      - staging-approval
    uses: jalts-808/j-hackers-app/.cloudbees/workflows/deployer.yaml
    with:
      manifest: ${{ inputs.manifest }}
      environment: j-hackers-k3s
    secrets: inherit
    vars: inherit

  run-smoke-tests:
    environment: j-hackers-k3s
    needs:
      - deploy-to-prod
    outputs:
      health-status: ${{ steps.health-check.outputs.status }}
    steps:
      - name: Production Health Check
        id: health-check
        uses: docker://alpine:3.20
        run: |
          apk add --no-cache curl

          echo "=== Production Health Check ==="

          # Check Web service
          echo "Checking Web service..."
          WEB_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://hackers-web.54.201.69.176.nip.io/ || echo "000")
          if [ "$WEB_STATUS" = "200" ]; then
            echo "Web service: UP (HTTP $WEB_STATUS)"
            WEB_HEALTH="UP"
          else
            echo "Web service: DOWN (HTTP $WEB_STATUS)"
            WEB_HEALTH="DOWN"
          fi

          # Check API service
          echo "Checking API service..."
          API_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://hackers-api.54.201.69.176.nip.io/api/stories || echo "000")
          if [ "$API_STATUS" = "200" ]; then
            echo "API service: UP (HTTP $API_STATUS)"
            API_HEALTH="UP"
          else
            echo "API service: DOWN (HTTP $API_STATUS)"
            API_HEALTH="DOWN"
          fi

          # Check Auth service
          echo "Checking Auth service..."
          AUTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://hackers-auth.54.201.69.176.nip.io/ || echo "000")
          if [ "$AUTH_STATUS" = "200" ] || [ "$AUTH_STATUS" = "404" ]; then
            echo "Auth service: UP (HTTP $AUTH_STATUS)"
            AUTH_HEALTH="UP"
          else
            echo "Auth service: DOWN (HTTP $AUTH_STATUS)"
            AUTH_HEALTH="DOWN"
          fi

          # Overall health
          if [ "$WEB_HEALTH" = "UP" ] && [ "$API_HEALTH" = "UP" ] && [ "$AUTH_HEALTH" = "UP" ]; then
            echo "HEALTHY" > $CLOUDBEES_OUTPUTS/status
            echo ""
            echo "All systems operational"
          else
            echo "DEGRADED" > $CLOUDBEES_OUTPUTS/status
            echo ""
            echo "Some systems experiencing issues"
          fi
      - name: Publish Smoke Test Evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |
            ## Production Smoke Test Results

            | Service | URL | Status |
            |---------|-----|--------|
            | Web | http://hackers-web.54.201.69.176.nip.io | ${{ steps.health-check.outputs.status }} |
            | API | http://hackers-api.54.201.69.176.nip.io | ${{ steps.health-check.outputs.status }} |
            | Auth | http://hackers-auth.54.201.69.176.nip.io | ${{ steps.health-check.outputs.status }} |

            **Overall Status**: ${{ steps.health-check.outputs.status }}

            ---
            **Release Complete** ✓
          format: MARKDOWN

  # NOTE: Feature flag rollout job removed - requires UNIFY_TOKEN secret
  # To re-enable, add UNIFY_TOKEN to j-hackers-k3s environment secrets
  # and uncomment enable-feature-flags job from full-release.yaml
